version: '3'
services:  
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=welcome$1234
      - MYSQL_USERNAME=root
    volumes:
      -./DATA:/VAR/LIB/mysql
    ports:
      -3306:3306
  appservice:
    build: ./boot
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/ems?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=welcome$1234
    ports:
      -8081:8081